### ISSUE TITLE
Broken on Safari

### ISSUE THREAD

**Issue by blackxored** [schlosser/substituteteacher.js#12]
Running this, or the demo site, on Safari doesn't work. Sentences never show, some words do, inconsistence behavior, never transitions.

**Comment by schlosser** [comment]
Looks like this is a problem with [`Animation._calculateWordWidth`](https://github.com/danrschlosser/substituteteacher.js/blob/master/src/substituteteacher.js#L923) being too small, and then `overflow:hidden` makes these disappear.
